/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as SyncLogsRouteImport } from './routes/sync.logs'
import { Route as LeadsIdRouteImport } from './routes/leads.$id'
import { Route as ApiPublicWpLeadRouteImport } from './routes/api/public/wp-lead'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncLogsRoute = SyncLogsRouteImport.update({
  id: '/sync/logs',
  path: '/sync/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIdRoute = LeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWpLeadRoute = ApiPublicWpLeadRouteImport.update({
  id: '/api/public/wp-lead',
  path: '/api/public/wp-lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/leads/$id': typeof LeadsIdRoute
  '/sync/logs': typeof SyncLogsRoute
  '/leads/': typeof LeadsIndexRoute
  '/api/public/wp-lead': typeof ApiPublicWpLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/leads/$id': typeof LeadsIdRoute
  '/sync/logs': typeof SyncLogsRoute
  '/leads': typeof LeadsIndexRoute
  '/api/public/wp-lead': typeof ApiPublicWpLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/leads/$id': typeof LeadsIdRoute
  '/sync/logs': typeof SyncLogsRoute
  '/leads/': typeof LeadsIndexRoute
  '/api/public/wp-lead': typeof ApiPublicWpLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/login'
    | '/settings'
    | '/leads/$id'
    | '/sync/logs'
    | '/leads/'
    | '/api/public/wp-lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/login'
    | '/settings'
    | '/leads/$id'
    | '/sync/logs'
    | '/leads'
    | '/api/public/wp-lead'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/login'
    | '/settings'
    | '/leads/$id'
    | '/sync/logs'
    | '/leads/'
    | '/api/public/wp-lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  LeadsIdRoute: typeof LeadsIdRoute
  SyncLogsRoute: typeof SyncLogsRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  ApiPublicWpLeadRoute: typeof ApiPublicWpLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync/logs': {
      id: '/sync/logs'
      path: '/sync/logs'
      fullPath: '/sync/logs'
      preLoaderRoute: typeof SyncLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$id': {
      id: '/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof LeadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wp-lead': {
      id: '/api/public/wp-lead'
      path: '/api/public/wp-lead'
      fullPath: '/api/public/wp-lead'
      preLoaderRoute: typeof ApiPublicWpLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  LeadsIdRoute: LeadsIdRoute,
  SyncLogsRoute: SyncLogsRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  ApiPublicWpLeadRoute: ApiPublicWpLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
